# This is a workflow to use secrets as variables

name: VariableSubstitution

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
      -name: Substitute Variables
      uses: microsoft/variable-substitution@v1 
      with:
        files: 'DataTransfer.py'
      env:
        DATA_ACCESS: ${{secrets.DATA_ACCESS}}
