# This is a workflow to use secrets as variables

name: VariableSubstitution
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/variable-substitution@v1 
        with:
          files: 'DataTransfer/TransferFiles.py'
    env:
        DATA_ACCESS: ${{secrets.DATA_ACCESS}}

